### ISSUE TITLE
 Timed out initializing process group in store based barrier

### ISSUE THREAD

**Issue by r00bit** [Noble-Lab/casanovo#217] opened 2023-07-22 00:30 UTC
Hello, 
When I installed casanovo and run on the train mode, it couldn't run the codes on the 4 GPUS though distribute the data on them. I mean when I used nvidia-smi it shows  that memory has data but the usage is zero and after a less than an hour it returns timeout error: 

```
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/112
Traceback (most recent call last):
  File "/home/x/miniconda3/envs/casanovo_env_3.2/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/casanovo/casanovo.py", line 259, in main
    model_runner.train(peak_path, peak_feature, peak_path_val, peak_feature_val, model, config)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 320, in train
    trainer.fit(
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1048, in _run
    self.strategy.setup_environment()
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 152, in setup_environment
    self.setup_distributed()
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 203, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/lightning_fabric/utilities/distributed.py", line 245, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 932, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/home/x/miniconda3/envs/casanovo_env_3.2/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 469, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=112, worker_count=1, timeout=0:30:00)
```

Since the code works on  other gpus, do you think if it happens because of the version of  pytorch-lightning not compatible with cuda? 
Thanks!

**Comment by bittremieux** [comment] 2023-07-22 18:45
Can you please share the full log?

Can you also provide some extra details about the dataset you're using for training? I suspect that loading the dataset on the individual GPUs takes longer than the time-out (30 minutes).

**Comment by r00bit** [comment] 2023-07-22 22:00
Please the file attached including log and error, thanks! 
I used mouse dataset as input. 
[bug-log.zip](https://github.com/Noble-Lab/casanovo/files/12137292/bug-log.zip)

**Comment by bittremieux** [comment] 2023-07-28 14:52
Thank you for sharing the log. I thought the training dataset might have been too large to read within the time-out window, but that doesn't seem to the case here.

Could you do the following things to help diagnose the issue:
- Does training work when using only a single GPU?
- After the progress bar related to reading the MGF file is no longer progressing, is there any activity on the GPU (`watch nvidia-smi`) or the CPU (`htop`)?

**Comment by r00bit** [comment] 2023-07-28 17:45
Hello, 
Thanks for following up!
So, the server that I am using has 4 gpus. The code could load the data on the gpus but couldn't run. The memory of each gpus is 
![Screenshot from 2023-07-22 14-50-44](https://github.com/Noble-Lab/casanovo/assets/44100934/2c02ae61-0044-4d0d-8d12-b6d2995861be)
occupied but the utilization is zero. I took a screenshot, please find the file attached, thanks!

**Comment by bittremieux** [comment] 2023-07-31 06:11
Does it run on the same system when using only a single GPU instead of all four? I.e. by using `CUDA_VISIBLE_DEVICES=0 casanovo --mode=...`.

**Comment by r00bit** [comment] 2023-07-31 14:49
I am getting another error before getting timeout error:
ValueError: `val_check_interval` (50000) must be less than or equal to the number of the training batches (928). If you want to disable validation set `limit_val_batches` to 0.0 instead.If you want to validate based on the total training batches, set `check_val_every_n_epoch=None`.
That's because of check_val_every_n_epoch added to new version. I am wondering how I can fix it, maybe remove it like the version 3.2.

**Comment by bittremieux** [comment] 2023-07-31 14:57
Yes, this will be fixed in #224.

To avoid the error, you can set `every_n_train_steps` to a value that's lower than the number of batches in your training data, i.e. smaller than 928.

**Comment by bittremieux** [comment] 2023-07-31 15:30
So with only a single GPU it is training successfully? That's a start and helps us figure out that at least it works on your system.

So that indicates that the issue is related to using multiple GPUs. We've used multiple GPUs regularly for training and haven't encountered this problem, so we'll need to dig a little deeper to try to reproduce it.

**Comment by r00bit** [comment] 2023-07-31 15:36
Yes, it works properly on single GPUs on a node. The code also works  on another server with 8 gpus.
For this server I should submit a job that' s the only difference.
Yeah, hope to learn how to fix it.

**Closed** 2023-08-16 10:58 UTC
Labels: bug
