### ISSUE TITLE
Casanovo Mztab file confirmation

### ISSUE THREAD

**Issue by Nkts007** [Noble-Lab/casanovo#155] opened 2023-03-29 12:43 UTC
Hi, 

I ran the casanovo code in the google colab environment and produced the file linked here, can i confirm that it was done correctly.  
(https://drive.google.com/file/d/1kgVxg17Mtwi4lyoBKsSDKkILNnOaxyiY/view?usp=share_link) 
I am concerned with the output as when i opened it on notepad, and there weren't peptide sequences, or PSM in the columns on the bottom of the file.  

Initially I thought it was running fine with the example file and that my experimental files were corrupted, but it seems the example file did not produce peptide sequences within the output file.

Can I get advice on this matter?

**Comment by bittremieux** [comment] 2023-03-29 13:46
Can you make your file on Google Drive publicly accessible? I get access denied at the moment.

**Comment by Nkts007** [comment] 2023-03-29 14:20
Hi I've edited the access on it!

Please advise me if there's any other access issues!

**Comment by bittremieux** [comment] 2023-03-29 15:02
The output is indeed incomplete. This indicates that Casanovo didn't finish successfully. The header information is written at the start of the execution (present in your file), whereas the PSMs are written after the data has been processed (missing in your file). So something happened that prevented Casanovo from completing.

Can you share the full Casanovo log file?

**Comment by Nkts007** [comment] 2023-03-30 17:05
Hi, I don't have the specific one for that run, but i re-ran the code and the output is the same, and the log in the folder here along side this run's output file

(https://drive.google.com/drive/folders/1LQrc4n2iZbMd5hvTp5_6EB1lRsJdpT-K?usp=sharing)

**Comment by bittremieux** [comment] 2023-03-31 07:59
Can you provide some more information how you ran Casanovo? There are a few aspects that are unclear to me:
- The log contains output for 4 executions of Casanovo. Did you run it multiple times?
- On line 95 in the log I see `UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...` Did you stop the execution at some point?
- I also don't see the final line you provided in the log, wheres normally the output and log should be identical.

**Comment by Nkts007** [comment] 2023-03-31 08:04
So I had ran it a few times, the run after the last keyboard interrupt was
the one I have with this file.

After the code had finished I downloaded a copy of the log , and then
waited 10- 15 minutes before downloading the files again and put those in
the folder, and I checked it once through again and there wasn't a change
on the log.

**Comment by bittremieux** [comment] 2023-03-31 09:34
Do you mind sharing your notebook from Colab so I can try to recreate the issue?

**Comment by Nkts007** [comment] 2023-03-31 13:09
(
https://colab.research.google.com/drive/1VD5cg6uC1xJj9J_GrHMuk6fVRMmKHUZ0?usp=share_link
)

Hi this is the link for the colab note book

Please note: there are some installations to help with the environment in
Google colab.

Also the spectra mgf file will need to be uploaded before casanovo reads it
- every time the session is cut, it deletes all the file in the notebook.

**Comment by bittremieux** [comment] 2023-04-03 09:45
I simplified the [Colab notebook](https://colab.research.google.com/drive/1peFY8Fl7Okt1mGqZiUdaBEkwd3zVmR_C?usp=sharing) a little bit, but I didn't have any issues running it.

One key thing to check is to make sure that you're using a Colab instance that has access to a GPU, as we're currently still solving a CPU-related bug (#106).

I'm going to close this issue, because I can't reproduce any problems. If problems persist on your end, please let us know.

**Closed by bittremieux** 2023-04-03 09:45 UTC
Labels: bug
