### ISSUE TITLE
Error with Casanovo

### ISSUE THREAD

**Issue by BenSamy2020** [Noble-Lab/casanovo#183] opened 2023-05-08 01:14 UTC
Greetings,

Thank you for providing this open source tool. I have been using the default setting of casanovo for most of my proteomics denovo analysis. Recently, I was interested to determine the suitabilitly for the use of Casanovo for immunopepetidomics. I changed the parameter file (config.yaml) to suit neoantigen target analysis pipeline. I experianced the error of this:

```
[parthiban@hpc-accel04 Casanovo]$ casanovo --mode=denovo --peak_path=/home/users/astar/imcb/parthiban/scratch/Casanovo/20230308_Parthiban_DMSO_1.mzML --output=/home/users/astar/imcb/parthiban/scratch/Casanovo/Output_DMSO_B1
[rank: 0] Global seed set to 454
2023-05-08 09:06:49,985 INFO [casanovo/MainProcess] casanovo._get_model_weights : Model weights file /home/users/astar/imcb/parthiban/.cache/casanovo/casanovo_massivekb_v3_0_0.ckpt retrieved from local cache
2023-05-08 09:06:49,985 INFO [casanovo/MainProcess] casanovo.main : Casanovo version 3.3.0
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : mode = denovo
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : model = /home/users/astar/imcb/parthiban/.cache/casanovo/casanovo_massivekb_v3_0_0.ckpt
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : peak_path = /home/users/astar/imcb/parthiban/scratch/Casanovo/20230308_Parthiban_DMSO_1.mzML
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : peak_path_val = None
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : config = default
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : output = /home/users/astar/imcb/parthiban/scratch/Casanovo/Output_DMSO_B1
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : random_seed = 454
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : n_peaks = 150
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : min_mz = 50.0
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : max_mz = 2500.0
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : min_intensity = 0.01
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : remove_precursor_tol = 2.0
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : max_charge = 4
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : precursor_mass_tol = 50.0
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : isotope_error_range = (0, 1)
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : min_peptide_len = 9
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : dim_model = 512
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : n_head = 8
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : dim_feedforward = 1024
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : n_layers = 9
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : dropout = 0.0
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : dim_intensity = None
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : custom_encoder = None
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : max_length = 10
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : residues = {'G': 57.021464, 'A': 71.037114, 'S': 87.032028, 'P': 97.052764, 'V': 99.068414, 'T': 101.04767, 'C': 103.009185, 'L': 113.084064, 'I': 113.084064, 'N': 114.042927, 'D': 115.026943, 'Q': 128.058578, 'K': 128.094963, 'E': 129.042593, 'M': 131.040485, 'H': 137.058912, 'F': 147.068414, 'R': 156.101111, 'Y': 163.063329, 'W': 186.079313, 'M+15.995': 147.0354, 'E-18.0106': 111.031993, 'C+119.0041': 222.013285, '+42.011': 42.010565, '-17.027': -17.026549}
2023-05-08 09:06:49,986 DEBUG [casanovo/MainProcess] casanovo.main : n_log = 1
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : tb_summarywriter = None
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : warmup_iters = 100000
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : max_iters = 600000
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : learning_rate = 0.0005
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : weight_decay = 1e-05
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : train_batch_size = 32
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : predict_batch_size = 1024
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : n_beams = 5
2023-05-08 09:06:49,987 DEBUG [casanovo/MainProcess] casanovo.main : top_match = 1
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : logger = None
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : max_epochs = 30
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : num_sanity_val_steps = 0
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : train_from_scratch = True
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : save_model = True
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : model_save_folder_path =
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : save_weights_only = True
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : every_n_train_steps = 50000
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : no_gpu = False
2023-05-08 09:06:49,996 DEBUG [casanovo/MainProcess] casanovo.main : n_workers = 48
2023-05-08 09:06:49,996 INFO [casanovo/MainProcess] casanovo.main : Predict peptide sequences with Casanovo.
2023-05-08 09:06:50,097 DEBUG [fsspec.local/MainProcess] local.__init__ : open file: /home/users/astar/imcb/parthiban/.cache/casanovo/casanovo_massivekb_v3_0_0.ckpt
Traceback (most recent call last):
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/casanovo/casanovo.py", line 165, in main
    model_runner.predict(peak_path, model, config, writer)
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 46, in predict
    _execute_existing(peak_path, model_filename, config, False, out_writer)
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 99, in _execute_existing
    model = Spec2Pep().load_from_checkpoint(
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 139, in load_from_checkpoint
    return _load_from_checkpoint(  # type: ignore[return-value]
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 188, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 247, in _load_state
    keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/home/users/astar/imcb/parthiban/.conda/envs/casanovo_env2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Spec2Pep:
        size mismatch for decoder.charge_encoder.weight: copying a param with shape torch.Size([10, 512]) from checkpoint, the shape in current model is torch.Size([4, 512]).
        size mismatch for decoder.aa_encoder.weight: copying a param with shape torch.Size([29, 512]) from checkpoint, the shape in current model is torch.Size([27, 512]).
        size mismatch for decoder.final.weight: copying a param with shape torch.Size([29, 512]) from checkpoint, the shape in current model is torch.Size([27, 512]).
        size mismatch for decoder.final.bias: copying a param with shape torch.Size([29]) from checkpoint, the shape in current model is torch.Size([27]).
```

Based on the error message I believe that the error message it appears that the shapes of the parameters in the current model are different from the shapes of the corresponding parameters in the saved checkpoint, which is causing the error. I may need to modify the current model to match the shapes of the saved checkpoint or obtain a new checkpoint with parameters that match the current model. Or be advice me on a work around with your current model? (I do not want to train a new model currently) Do you hav any model that is suitable for immunopeptidomics analysis? I believe you tool has amasing potential in immunopeptidomics/neoantigen discovery space.

Regards,
Ben.

**Comment by bittremieux** [comment] 2023-05-08 04:15
The problem is that you changed the residue alphabet. Casanovo needs to know what each residue means, so this is not possible without retraining the model. Therefore, I would recommend that you revert the residue changes to be able to run Casanovo.

We have weights for an internal non-enzymatic model, which should be better than the default tryptic model for immunopeptidomics analyses. These will be released soon, after we have implemented functionality to automatically download different weights (#108).

**Closed by bittremieux** 2023-05-08 04:15 UTC
