### ISSUE TITLE
MacOS error: Rank of updates array (1) must be greater than or equal to inner-most dimension of indices array (29)

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#260] opened 2023-10-30 15:02 UTC
I am running on the dev branch and getting an error on MacOS that does not appear when I run under Linux.

```
PYTORCH_ENABLE_MPS_FALLBACK=1
casanovo sequence --model epoch=5-step=400000.ckpt 03022016_Clara_MP_Fraction_03.mgf
Seed set to 454
INFO: Casanovo version 3.3.1.dev26+g7721962
INFO: Sequencing peptides from:
INFO:   03022016_Clara_MP_Fraction_03.mgf
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
INFO: Reading 1 files...
03022016_Clara_MP_Fraction_03.mgf: 10164spectra [00:00, 17147.83spectra/s]
WARNING: Skipped 33 spectra with invalid precursor info
Predicting DataLoader 0:   0%|                           | 0/10 [00:00<?, ?it/s]
WARNING: UserWarning: The operator 'aten::_nested_tensor_from_mask_left_aligned' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:13.)
/AppleInternal/Library/BuildRoots/d9889869-120b-11ee-b796-7a03568b17ac/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSNDArray/Kernels/MPSNDArrayGatherND.mm:234: failed assertion `Rank of updates array (1) must be greater than or equal to inner-most dimension of indices array (29)'
/opt/homebrew/Caskroom/miniconda/base/envs/denovofdr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I am using 

```
casanovo version
Casanovo: 3.3.1.dev26+g7721962
Depthcharge: 0.2.3
Lightning: 2.1.0
PyTorch: 2.1.0
```

[03022016_Clara_MP_Fraction_03.mgf.txt](https://github.com/Noble-Lab/casanovo/files/13206595/03022016_Clara_MP_Fraction_03.mgf.txt)

I can't upload the ckpt file because it's too big, but I can send it.

**Comment by bittremieux** [comment] 2024-02-10 08:45
Duplicate of #285.

**Closed by bittremieux** 2024-02-10 08:45 UTC
Labels: bug
