### ISSUE TITLE
TypeError: Can't implicitly convert non-string objects to strings

### ISSUE THREAD

**Issue by wsnoble** [Noble-Lab/casanovo#221] opened 2023-07-28 17:19 UTC
Something must be wrong with my MGF file, but I can't figure out what it is.  Here is the command and the traceback:

```
$ casanovo  train sample.mgf --validation_peak_path sample.mgf
Global seed set to 454
INFO: Casanovo version 3.3.1.dev13+gad48a09
INFO: Training a model from:
INFO:   sample.mgf
INFO: Using the following validation files:
INFO:   sample.mgf
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
INFO: Reading 1 files...
sample.mgf: 37spectra [00:00, 1111.13spectra/s]
Traceback (most recent call last):
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/bin/casanovo", line 8, in <module>
    sys.exit(main())
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/casanovo/casanovo.py", line 217, in train
    runner.train(train_peak_path, validation_peak_path)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 101, in train
    train_index = self._get_index(train_peak_path, True, "training")
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/casanovo/denovo/model_runner.py", line 357, in _get_index
    return Index(index_fname, filenames, valid_charge=valid_charge)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 446, in __init__
    super().__init__(
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 104, in __init__
    self.add_file(ms_file)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/depthcharge/data/hdf5.py", line 231, in add_file
    group.create_dataset(
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/net/noble/vol1/home/noble/miniconda3/envs/casanovo_dev/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 166, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 283, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 145, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 444, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 95, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 249, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings

```

The MGF file is attached.
[sample.mgf.txt](https://github.com/Noble-Lab/casanovo/files/12196740/sample.mgf.txt)

I am running with this version:
```
Casanovo: 3.3.1.dev13+gad48a09
Depthcharge: 0.2.2
Lightning: 2.0.5
PyTorch: 2.0.1+cu117
```

**Comment by wsnoble** [comment] 2023-07-28 17:20
Incidentally, I verified that the same error appears on Linux (CentOS) and MacOS.

**Comment by wsnoble** [comment] 2023-07-28 17:26
Ah! I figured it out.  The peptide line is supposed to be "SEQ=." We should fix the error message to make it clear that no peptide sequence was found in the MGF file.

**Comment by bittremieux** [comment] 2023-07-31 08:59
Duplicate of #207

**Closed by bittremieux** 2023-07-31 08:59 UTC
Labels: enhancement
